language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: hooandee-toxtricity
  api_key:
    secure: l6Ik/X22YouoO4Dm0nW6m2dXzPM+kc0rJe60TEHBegde7cRAr3l6CyNnE3TVbgu+rEaLpxkO8zJhEf/HA9WNKCYUk4Pff5pk9CdfydRBRXqquybvkJBLhS6q+J31I5olNM3plVCNtQ1mWAXNswDNyrmvm0fjDyrIghwKDHXeCw0gneVJSZ7S1Sd2OTHdFQ5Yng0RAyVr5ttN2Slr2jh2PiZ8fjC2gDn1X2Ee2ojeL6KGaDWLGP5hyMdCS2iF+ZgrOhCeGaEdOtoEaO8TWc0RD16DIm9/dK8dLuO35wyGIZgTLL68yEZ7fOuYRnUMK8QxAd8twkmBIPGFM//zCn2LJ6PmPYFHFZ7irQ63kzBwOfwUhS7Z3tALxmI1OnS+GGudNIr+odQvvU79hKq7jpIUsnxhc4TEYRoH/kOBd//Jh0wKUJ7AHV2hoPeJYBsRlkrNoWkDxCpQqNI/EPGBbbJJ54BkFwAzm/VvjVH7kB8/CBva/5rYmAFgmTs2IIaSDkrCTM1d0kpn6lzXirKxokgKJ8VhJ8TtfAGzNyizBpV5tJPrhtAxihsTAbzXj2uCZodv0GR9iAnJghYk3d9R4oQyCOUDpY1/dqeiSr2no4a73A03aImjlokubHc/7qPlI4bWgwyraRQIaS1mvstH00Wvld+C1w2xSY5jLb81CGz6jCo=
